spring:
  #jpa mysql
  datasource:
    url: jdbc:mysql://localhost:3306/demo-zalo-part1?createDatabaseIfNotExist=true
    username: root
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  #Thay đổi tự cập nhật frontend
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


#hibernate jwt
application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3bde6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
    refreshToken:
      tokenValidityMilliseconds: 259200000
